### PR TITLE
Adding C++

### PR DESCRIPTION
**Pull request by czhanacek**
**Which language are you adding? (If it's not widely known, or rather esoteric, can you provide a link to more information?**
C++

**Things to make sure of:**

1. Did you create a new directory containing all the necessary files to run your hello world? 
Yep
2. Does your addition have a readme with the same format as [this example](https://github.com/wsu-lug/hello-world/blob/master/go/readme.md), including the language, instructions, and a screenshot of it running? 
Yes

### CODE REVIEW

**Comment by czhanacek** [comment]
Forgot to make my readme look more like yours. Fixed now.

**Comment by matmerr** [comment]
I feel like the .plist and settings.json don't contribute to the hello world :)

**Comment by czhanacek** [comment]
Should be all ready to go :)

**Comment by matmerr** [comment]
Mind squashing these commits into one so the log is a little cleaner? Thanks!

For reference: http://stackoverflow.com/a/5201642/295797

**Comment by czhanacek** [comment]
squashed like a 🐛

**Comment by matmerr** [comment]
/lgtm

noice 👍

**Pull request merged**
